apiVersion: actions.summerwind.dev/v1alpha1
kind: RunnerDeployment
metadata:
  name: actions-runner-kubefirst
  annotations:
    argocd.argoproj.io/sync-wave: "20"
spec:
  replicas: 2
  template:
    spec:  
      repository: jarededwards/gitops # todo replace this
      image: summerwind/actions-runner-dind
      serviceAccountName: github-runner
      dockerdWithinRunnerContainer: true
      automountServiceAccountToken: true